name:                back-end
version:             0.1.0.0
github:              "githubuser/back-end"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/back-end#readme>

dependencies:
- base >= 4.7 && < 5
- text
- time
- mtl
- containers
- bytestring
- aeson
- random
- hspec 
- async
- stm
- hashable
- websockets
- dotenv
- exceptions
- either
- resource-pool
- data-has
- unliftio
- template-haskell
- postgresql-simple
- postgresql-simple-migration
- string-random
# - record-dot-preprocessor
# - aeson


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  back-end-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - back-end

tests:
  back-end-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - back-end
